# Generated by Django 5.0 on 2023-12-06 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.tag')),
            ],
            bases=('shared.tag',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=4095)),
                ('cost', models.IntegerField()),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.tasktag')),
            ],
        ),
    ]
